substitutions:
  name: "seeedstudio-mmwave-kit"
  friendly_name: "SeeedStudio mmWave Kit"

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: true
  project:
    name: "seeedstudio.mmwave_kit"
    version: "3.0"
  platformio_options:
    board_build.flash_mode: dio
    board_build.mcu: esp32c3

#external_components:
#  - source:
#      type: git
#      url: https://github.com/pinkfish/MR24HPC1_ESPHome_external_components
#      ref: main
#    refresh: 0s

esp32:
  board: esp32-c3-devkitm-1
  variant: esp32c3
  framework:
    type: esp-idf

# Enable logging
logger:
  hardware_uart: USB_SERIAL_JTAG
  level: DEBUG

# Enable Home Assistant API
api:

ota:
  - platform: esphome

wifi:
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "seeedstudio-mr24hpc1"

captive_portal:

# Sets up Bluetooth LE (Only on ESP32) to allow the user
# to provision wifi credentials to the device.
esp32_improv:
  authorizer: none

# Sets up the improv via serial client for Wi-Fi provisioning.
# Handy if your device has a usb port for the user to add credentials when they first get it.
# improv_serial: # Commented until improv works with usb-jtag on idf

uart:
  id: uart_bus
  baud_rate: 115200
  rx_pin: 4
  tx_pin: 5
  parity: NONE
  stop_bits: 1

seeed_mr24hpc1:
  id: my_seeed_mr24hpc1

text_sensor:
  - platform: seeed_mr24hpc1
    heart_beat:
      name: "Heartbeat"
    product_model:
      name: "Product Model"
    product_id:
      name: "Product ID"
    hardware_model:
      name: "Hardware Model"
    hardware_version:
      name: "Hardware Version"
    keep_away:
      name: "Current Proximity"
    motion_status:
      name: "Motion Information"

binary_sensor:
  - platform: seeed_mr24hpc1
    has_target:
      name: "Presence Information"
      device_class: occupancy

sensor:
  - platform: seeed_mr24hpc1
    movement_signs:
      name: "Body Movement Parameter"
    existence_energy:
      name: "Existence Energy"
    motion_energy:
      name: "Motion Energy"
    motion_speed:
      name: "Motion Speed"
    motion_distance:
      name: "Motion Distance"
    static_distance:
      name: "Static Distance"

button:
  - platform: seeed_mr24hpc1
    restart:
      name: "Module Restart"

select:
  - platform: seeed_mr24hpc1
    scene_mode:
      name: "Scene"
    motion_timeout:
      name: "Presence timeout"

number:
  - platform: seeed_mr24hpc1
    sensitivity:
      name: "Sensitivity"